version: '3.8'
services:
  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=test1234!
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "test1234!"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf