version: '3.8'
services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cryptolab1234!
      POSTGRES_DB: quant_db
    ports:
      - "5432:5432"
    volumes:
      - crypto_db:/var/lib/postgresql/data
volumes:
  crypto_db: {}